### PR TITLE
Validate credentials and handle mpx connection errors

### LINKED ISSUE #16: Catch credential exceptions when triggered from the UI
These should be caught, logged, and printed as a message.

### PR DESCRIPTION
**Pull request by deviantintegral**
This PR resolves #16 by:

* Checks the username and password when saving the mpx user form.
* Adds error handling catching HTTP errors to the User, Account, and Player Formatter Settings forms.
* Handles errors when rendering players, logging the exception and continuing to the next item in the list.

### CODE REVIEW

File: src/Form/AccountForm.php [hunk 1]
```diff
@@ -233,19 +250,72 @@ private function loadMpxUsers(FormStateInterface $form_state): array {
    *     - The account options.
    *     - The account public IDs.
    */
-  private function accountOptions(FormStateInterface $form_state): array {
-    $user_entity_id = $form_state->getValue('user');
+  protected function accountOptions(FormStateInterface $form_state): array {
+    try {
+      try {
```
Comment (juampynr) [inline src/Form/AccountForm.php:255]: Interesting: I have never seen a try within a try.

Comment (deviantintegral) [reply src/Form/AccountForm.php:255]: Yeah, I try to avoid it, but it's the only way to handle catching an exception and then deciding you need to re-throw it for a more general handler.
