### PR TITLE
Issue #115 Handle the case when no notifications are returned from mpx in a timeout scenario

### LINKED ISSUE #115: TypeError in NotificationQueuer on connection timeout, when no notifications are returned
We have a need to set a timeout on the MPX client HTTP connection. By default the timeout is infinite:
https://github.com/Lullabot/media_mpx/blob/8.x-1.x/src/ClientFactory.php#L88. That relies on MPX eventually closing the connection. However in our environment, MySQL has a 10 minute `wait_timeout` and `interactive_timeout` and that means that in some situations the connection to MySQL dies before the HTTP connection to MPX relinquishes. As such, we set the timeout for the MPX connection to less than 10m.

This revealed  bug in `\Drupal\media_mpx\Commands\NotificationQueuer::doListen` where it doesn't correctly handle an empty return from `\Drupal\media_mpx\NotificationListener::listen`. In that case we get the following error:

```
 [error]  Error: Call to a member function isSyncResponse() on boolean in Drupal\media_mpx\Commands\NotificationQueuer->doListen() (line 283 of /var/www/web/modules/contrib/media_mpx/src/Commands/NotificationQueuer.php) #0 /var/www/web/modules/contrib/media_mpx/src/Commands/NotificationQueuer.php(89): Drupal\media_mpx\Commands\NotificationQueuer->doListen('mpx_feed_config', true)
#1 [internal function]: Drupal\media_mpx\Commands\NotificationQueuer->listen('mpx_feed_config', Array)
#2 /var/www/vendor/consolidation/annotated-command/src/CommandProcessor.php(257): call_user_func_array(Array, Array)
#3 /var/www/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#4 /var/www/vendor/consolidation/annotated-command/src/CommandProcessor.php(178): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#5 /var/www/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(302): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#6 /var/www/vendor/symfony/console/Command/Command.php(255): Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/vendor/symfony/console/Application.php(978): Symfony\Component\Console\Command\Command->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/vendor/symfony/console/Application.php(255): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/vendor/drush/drush/src/Runtime/Runtime.php(112): Symfony\Component\Console\Application->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/vendor/drush/drush/src/Runtime/Runtime.php(41): Drush\Runtime\Runtime->doRun(Array)
#12 /var/www/vendor/drush/drush/drush.php(66): Drush\Runtime\Runtime->run(Array)
#13 /var/www/vendor/drush/drush/drush(4): require('/var/www/vendor...')
#14 {main}. 
Error: Call to a member function isSyncResponse() on boolean in /var/www/web/modules/contrib/media_mpx/src/Commands/NotificationQueuer.php on line 283 #0 /var/www/web/modules/contrib/media_mpx/src/Commands/NotificationQueuer.php(89): Drupal\media_mpx\Commands\NotificationQueuer->doListen('mpx_feed_config', true)
#1 [internal function]: Drupal\media_mpx\Commands\NotificationQueuer->listen('mpx_feed_config', Array)
#2 /var/www/vendor/consolidation/annotated-command/src/CommandProcessor.php(257): call_user_func_array(Array, Array)
#3 /var/www/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
```

### PR DESCRIPTION
**Pull request by m4olivei**
Resolves #115.

### CODE REVIEW

File: src/Commands/NotificationQueuer.php [hunk 1]
```diff
@@ -274,24 +274,50 @@ private function doListen($media_type_id, bool $once = FALSE): void {
...
+   * @param bool $once
+   *   (optional) Run once instead of until all notifications are processed.
+   *
+   * @return bool
+   *   TRUE if there are more notifications to consume, otherwise FALSE.
+   */
+  private function processNotifications(array $notifications, MediaTypeInterface $media_type, bool $once = FALSE): bool {
+    // We did not receive any notifications, connection may have timed out.
+    if (empty($notifications)) {
+      $this->logger()->info(dt('Connection to MPX has timed out.'));
```
Comment (deviantintegral) [inline src/Commands/NotificationQueuer.php]: `mpx`, not `MPX`.

I don't think we need to wrap this in `dt()`, because the log call already has `$context` for replacements?

File: src/Commands/NotificationQueuer.php [hunk 2]
```diff
@@ -274,24 +274,50 @@ private function doListen($media_type_id, bool $once = FALSE): void {
...
+      $this->io()->note(dt('Connection to MPX has timed out.'));
```
Comment (deviantintegral) [inline src/Commands/NotificationQueuer.php]: Seems odd to do this twice. If I use `--verbose` I'll see this message twice. Perhaps remove the log call entirely?

File: src/Commands/NotificationQueuer.php [hunk 3]
```diff
@@ -274,24 +274,50 @@ private function doListen($media_type_id, bool $once = FALSE): void {
...
-      // @see https://docs.theplatform.com/help/wsf-subscribing-to-change-notifications#tp-toc10
-      if ($last_notification->isSyncResponse()) {
-        $this->logger()->info(dt('All notifications have been processed.'));
-        $more_to_consume = FALSE;
-      }
-      else {
-        $this->filterAndQueue($media_type, $notifications);
-        $more_to_consume = !$once;
-      }
+      $more_to_consume = $this->processNotifications($notifications, $media_type, $once);
```
Comment (deviantintegral) [inline src/Commands/NotificationQueuer.php]: What do you think about changing this to a do / while loop?

File: src/Commands/NotificationQueuer.php (hunk 1 above)
Comment (m4olivei) [reply src/Commands/NotificationQueuer.php]: I think I followed what Drush core was doing most often, eg.

https://github.com/drush-ops/drush/search?q=%22logger%28%29-%3Einfo%22&unscoped_q=%22logger%28%29-%3Einfo%22

File: src/Commands/NotificationQueuer.php (hunk 2 above)
Comment (m4olivei) [reply src/Commands/NotificationQueuer.php]: Yeah, will do, thanks.

**Review by deviantintegral — COMMENTED** [review]
This looks good. As we're fixing a bug it'd be good to write a test for this.
