### PR TITLE
Issue #97 Set a max age of at most ten years

### LINKED ISSUE #97: Really far out expiration dates can break that cause errors with caching
For MPX media that have really far out expiration dates, the delta between now and the expiration is such a large value that using it as a cache max age throws errors:

```
Please try again later.</br></br><em class="placeholder">Drupal\Core\Database\DatabaseExceptionWrapper</em>: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column &#039;expire&#039; at row 1: INSERT INTO {cache_render} (cid, expire, created, tags, checksum, data, serialized) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6) ON DUPLICATE KEY UPDATE cid = VALUES(cid), expire = VALUES(expire), created = VALUES(created), tags = VALUES(tags), checksum = VALUES(checksum), data = VALUES(data), serialized = VALUES(serialized); Array

...
```

### PR DESCRIPTION
**Pull request by m4olivei**
Resolves #97

### CODE REVIEW

File: src/Access/MediaAvailableAccess.php [hunk 1]
```diff
@@ -133,12 +135,20 @@ protected function mergeCacheMaxAge(MpxMedia $mpx_media, MediaInterface $media)
     $available_date = $mpx_media->getAvailableDate();
     if ($available_date instanceof ConcreteDateTime &&
       $now < $available_date->getDateTime()) {
-      $media->mergeCacheMaxAge($available_date->getDateTime()->getTimestamp() - $now->getTimestamp());
+      $delta = $available_date->getDateTime()->getTimestamp() - $now->getTimestamp();
+      // Safe guard against radically far out dates. Set the max age to the min
```
Comment (deviantintegral) [inline src/Access/MediaAvailableAccess.php:139]: This is amazing. In particular that you've managed to use the word "radical" in such a "far out" PR.

**Review by deviantintegral — APPROVED** [review]

File: src/Access/MediaAvailableAccess.php (hunk 1 above)
Comment (mattwith) [reply src/Access/MediaAvailableAccess.php:139]: Ha! 👍
